apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: rest-app-service
  externalIPs:
    - 3.142.46.13
