apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: rest-app-service
